name: CI / Production

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  deploy-storybook:
    name: deploy storybook to production
    environment:
      name: Storybook - production
      url: https://purrfect-ui-prod.vercel.app/
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: storybook
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          GITHUB_DEPLOYMENT: false
          PRODUCTION: false
          ALIAS_DOMAINS: |
            purrfect-ui-prod.vercel.app
